workflows:
  android-build:
    name: Android Build

    environment:
      node: 22
      java: 21
    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android && chmod +x gradlew && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
